{application,lab3,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{lab3,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[function_generator,input_reader,lab3,lab3_sup,
                        math_logger,points_generator]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
